export function guideText(): string {
	return [
		"mu guide - in-CLI documentation",
		"",
		"Goal: you should not have to leave the CLI to understand what mu supports.",
		"",
		"Most read/list/mutation interfaces default to compact output; add --json for full machine records.",
		"",
		"Quickstart",
		"  1) Inspect current state:",
		"       mu status",
		"       mu issues ready --root <root-id>",
		"",
		"  2) Execute one-shot operator work:",
		"       mu exec \"summarize ready issues and propose next actions\"",
		"",
		"  3) Continue execution via sessions/turns:",
		"       mu session list",
		"       mu turn --session-id <id> --body \"continue from previous state\"",
		"",
		"Agent Navigation (by intent)",
		"  Inspect current state:",
		"    mu status --pretty",
		"    mu issues list --status open --limit 20",
		"    mu heartbeats list --limit 20",
		"    mu cron stats",
		"",
		"  Pull memory/context across stores:",
		"    mu memory search --query <text> --limit 20",
		"    mu memory timeline --issue-id <id> --order desc --limit 40",
		"    mu memory stats --source events",
		"",
		"  Keep memory index fresh:",
		"    mu memory index status",
		"    mu memory index rebuild",
		"    (queries auto-heal missing index; mu serve maintains stale-index repairs on a schedule)",
		"",
		"Command Overview",
		"  mu status                       Human summary (or JSON with --json)",
		"  mu store <subcmd>               Inspect workspace store files (paths/ls/tail)",
		"  mu issues <subcmd>              Work item operations",
		"  mu forum <subcmd>               Coordination message operations",
		"  mu exec <prompt...>             One-shot operator prompt",
		"  mu session [list|<id>]          Reconnect/list terminal operator sessions",
		"  mu session config <subcmd>      Session-scoped model/thinking settings",
		"  mu turn [opts]                  Inject one turn into an existing session",
		"  mu replay <id|path>             Print a logged run",
		"  mu control <subcmd>             Messaging integration identity/config",
		"  mu control config <subcmd>      Workspace control-plane config surface",
		"  mu control harness              Provider/model capability snapshot",
		"  mu heartbeats <subcmd>          Heartbeat program lifecycle",
		"  mu cron <subcmd>                Cron program lifecycle",
		"  mu serve                        Start API + terminal operator session",
		"  mu login                        Authenticate with an AI provider",
		"",
		"Workspace Store Layout",
		"  mu stores runtime state under ~/.mu/workspaces/<workspace-id>/ :",
		"    <store>/",
		"      .gitignore    Auto-generated runtime-state guard",
		"      issues.jsonl   Issue DAG nodes (one JSON object per line)",
		"      forum.jsonl    Forum messages (one JSON object per line)",
		"      events.jsonl   Append-only event log (auditing / derived views)",
		"      logs/          Run logs",
		"",
		"  Logs are written under:",
		"    <store>/logs/<root-id>/<issue-id>*.jsonl",
		"",
		"Common Workflows",
		"",
		"  Status",
		"    mu status",
		"    mu status --verbose",
		"    mu status --json --pretty",
		"",
		"  Store inspection (workspace store)",
		"    mu store paths",
		"    mu store ls --pretty",
		"    mu events list --limit 20",
		"    mu store tail cp_operator_turns --limit 20        (compact preview)",
		"    mu store tail cp_operator_turns --limit 20 --raw  (exact rows)",
		"",
		"  Memory index",
		"    mu memory index status",
		"    mu memory index rebuild",
		"    mu memory search --query reload --limit 20",
		"    (search/timeline/stats become index-first when index exists)",
		"",
		"  Work items",
		'    mu issues create "Title" --body "Details" --priority 2 --tag node:agent',
		"    mu issues list --status open --limit 20",
		"    mu issues ready --root <root-id>",
		"    mu issues get <id-or-prefix> --pretty",
		"    mu issues update <id> --status in_progress",
		"    mu issues close <id> --outcome success",
		"",
		"  Forum",
		'    mu forum post issue:<id> -m "status update" --author operator',
		"    mu forum read issue:<id> --limit 20",
		"    mu forum topics --prefix issue: --limit 20",
		"",
		"  Operator workflows",
		"    mu exec <prompt...>",
		"    mu session list",
		"    mu turn --session-kind operator --session-id <session-id> --body \"follow-up\"",
		"",
		"  Heartbeats (periodic operator wake)",
		"    mu heartbeats list --limit 20",
		'    mu heartbeats create --title "Telegram heartbeat" --prompt "Review open issues and post next actions" --every-ms 300000 --reason telegram_heartbeat',
		"    mu heartbeats trigger <program-id> --reason smoke_test",
		"    mu heartbeats disable <program-id>",
		"",
		"  Cron programs",
		"    mu cron stats",
		"    mu cron list --enabled true --limit 20",
		"    mu cron trigger <program-id> --reason smoke_test",
		"",
		"  Operator sessions",
		"    mu session                   Reconnect to the latest operator session",
		"    mu session list              List persisted sessions (operator + cp_operator)",
		"    mu session list --kind cp_operator",
		"    mu session list --kind all --all-workspaces --limit 50",
		"    mu session list --verbose    Show per-row kind chips (op/cp)",
		"    mu session --new             Start a fresh operator session",
		"    mu session <session-id>      Reconnect to a specific session (auto-resolves operator/cp)",
		"    mu session config get --session-id <id>",
		"    mu session config set-model --session-id <id> --provider <p> --model <m>",
		"    mu session config set-thinking --session-id <id> --thinking minimal",
		"",
		"  Replay",
		"    mu replay <root-id>/<issue-id>                     (bounded preview)",
		"    mu replay <store>/logs/<root-id>/<issue-id>.jsonl --raw",
		"    mu replay <store>/logs/<root-id>/<issue-id>.jsonl --all --raw   (full dump)",
		"",
		"  Messaging integrations (identity & config)",
		"    mu control status                      Compact summary of identities, policy, adapters",
		"    mu control status --verbose            Expanded adapter/operator detail",
		"    mu control status --json --pretty      Structured output",
		"    mu control config get                  Compact typed workspace config values",
		"    mu control config get --verbose        Include defaults + descriptions",
		"    mu control config set control_plane.operator.enabled false",
		"    mu control config unset control_plane.adapters.slack.bot_token",
		"    mu control harness                     Compact harness/provider capability snapshot",
		"    mu control harness --verbose           Expanded adapter/default-model/model vectors",
		"    mu control harness openai-codex        Focus one provider's model catalog",
		"    mu control link --channel telegram --actor-id 123 --tenant-id telegram-bot",
		"    mu control link --channel slack --actor-id U01 --tenant-id T01 --role viewer",
		"    mu control identities                  Compact active binding table",
		"    mu control identities --all            Include inactive bindings",
		"    mu control identities --all --json --pretty",
		"    mu control unlink <binding-id>          Self-unlink",
		"    mu control unlink <binding-id> --revoke Admin revocation",
		"    mu control diagnose-operator            Inspect operator turn parse/runtime health",
		"",
		"  Serve (API + terminal operator session)",
		"    mu serve",
		"    mu serve --port 3000",
		"    (mu serve immediately attaches terminal operator session; /exit/Ctrl+D/Ctrl+C detaches, server stays running)",
		"",
		"  Login / Auth",
		"    mu login --list",
		"    mu login openai-codex",
		"",
		"Troubleshooting",
		"  Store missing / empty:",
		"    Run `mu serve` or `mu session` once to auto-create workspace store files.",
		"",
		"  Ambiguous id prefix:",
		"    Use a longer prefix or the full id. Try: `mu issues list --limit 20`.",
		"",
		"  Reconnect terminal operator after disconnect:",
		"    Use `mu session` (or `mu session <session-id>`). Interactive mode requires a TTY.",
		"",
		"  Headless/SSH serve:",
		"    Port-forward the serve port as needed.",
		"    The same terminal hosts the operator session.",
		"",
		"  Too much ANSI color:",
		"    Set `NO_COLOR=1` (or unset it to re-enable color).",
	].join("\n");
}
