export function guideText(): string {
	return [
		"mu guide - in-CLI documentation",
		"",
		"Goal: you should not have to leave the CLI to understand what mu supports.",
		"",
		"Most read/list/mutation interfaces default to compact output; add --json for full machine records.",
		"",
		"Quickstart",
		"  1) Start a run (auto-initializes workspace store, starts serve lifecycle, queues run, attaches operator terminal):",
		'       mu run "Break down this goal and execute it"',
		"",
		"  2) See what exists / what is ready:",
		"       mu status",
		"       mu issues ready --root <root-id>",
		"",
		"  3) Resume an interrupted run:",
		"       mu resume <root-id>",
		"",
		"Agent Navigation (by intent)",
		"  Inspect current state:",
		"    mu status --pretty",
		"    mu issues list --status open --limit 20",
		"    mu runs list --status running --limit 20",
		"",
		"  Pull memory/context across stores:",
		"    mu memory search --query <text> --limit 20",
		"    mu memory timeline --issue-id <id> --order desc --limit 40",
		"    mu memory stats --source events",
		"",
		"  Keep memory index fresh:",
		"    mu memory index status",
		"    mu memory index rebuild",
		"    (queries auto-heal missing index; mu serve maintains stale-index repairs on a schedule)",
		"",
		"Command Overview",
		"  mu status                       Human summary (or JSON with --json)",
		"  mu store <subcmd>               Inspect workspace store files (paths/ls/tail)",
		"  mu issues <subcmd>              Work item operations",
		"  mu forum <subcmd>               Coordination message operations",
		"  mu run <prompt...>              Queue a run + attach operator terminal",
		"  mu exec <prompt...>             One-shot operator prompt (no queued run)",
		"  mu resume <root-id>             Resume a run",
		"  mu session [list|<id>]          Reconnect/list terminal operator sessions",
		"  mu replay <id|path>             Print a logged run",
		"  mu control <subcmd>             Messaging integration identity/config",
		"  mu serve                        Start API + terminal operator session",
		"  mu login                        Authenticate with an AI provider",
		"",
		"Workspace Store Layout",
		"  mu stores runtime state under ~/.mu/workspaces/<workspace-id>/ :",
		"    <store>/",
		"      .gitignore    Auto-generated runtime-state guard",
		"      issues.jsonl   Issue DAG nodes (one JSON object per line)",
		"      forum.jsonl    Forum messages (one JSON object per line)",
		"      events.jsonl   Append-only event log (auditing / derived views)",
		"      logs/          Run logs (grouped by root issue id)",
		"",
		"  Logs are written under:",
		"    <store>/logs/<root-id>/<issue-id>*.jsonl",
		"",
		"Common Workflows",
		"",
		"  Status",
		"    mu status",
		"    mu status --json --pretty",
		"",
		"  Store inspection (workspace store)",
		"    mu store paths",
		"    mu store ls --pretty",
		"    mu store tail events --limit 20",
		"    mu store tail cp_operator_turns --limit 20 --json --pretty",
		"",
		"  Memory index",
		"    mu memory index status",
		"    mu memory index rebuild",
		"    mu memory search --query reload --limit 20",
		"    (search/timeline/stats become index-first when index exists)",
		"",
		"  Work items",
		'    mu issues create "Title" --body "Details" --priority 2 --tag node:agent',
		"    mu issues list --status open --limit 20",
		"    mu issues ready --root <root-id>",
		"    mu issues get <id-or-prefix> --pretty",
		"    mu issues update <id> --status in_progress",
		"    mu issues close <id> --outcome success",
		"",
		"  Forum",
		'    mu forum post issue:<id> -m "status update" --author worker',
		"    mu forum read issue:<id> --limit 20",
		"    mu forum topics --prefix issue: --limit 20",
		"",
		"  Run / Resume",
		"    mu run <prompt...> --max-steps 20",
		"    mu exec <prompt...>",
		"    mu runs list --status running --limit 20",
		"    mu resume <root-id> --max-steps 20",
		"",
		"    Model overrides (queued run intent + attached operator session):",
		'      mu run "..." --provider openai-codex --model gpt-5.3-codex --reasoning high',
		"",
		"    Note: `mu run --json` and `mu run --raw-stream` were removed.",
		"    For machine integration, use `mu serve` and call /api/control-plane/runs/*.",
		"    Use `mu exec` for lightweight one-shot operator work without queuing a run.",
		"",
		"  Heartbeats (periodic operator wake)",
		"    mu heartbeats list --limit 20",
		"    mu heartbeats create --title \"Telegram heartbeat\" --prompt \"Review open issues and post next actions\" --every-ms 300000 --reason telegram_heartbeat",
		"    mu heartbeats trigger <program-id> --reason smoke_test",
		"    mu heartbeats disable <program-id>",
		"",
		"    Telegram setup checklist:",
		"      1) mu control status",
		"      2) mu control link --channel telegram --actor-id <chat-id> --tenant-id telegram-bot",
		"      3) mu heartbeats create --title \"Telegram heartbeat\" --prompt \"Review open issues and post next actions\" --every-ms 300000 --reason telegram_heartbeat",
		"",
		"  Operator sessions",
		"    mu session                   Reconnect to the latest operator session",
		"    mu session list              List persisted operator sessions",
		"    mu session --new             Start a fresh operator session",
		"    mu session <session-id>      Reconnect to a specific session",
		"",
		"    Operator behavior is configured in <store>/config.json",
		"    Use direct CLI commands in chat (for example: mu control status, mu session list)",
		"",
		"    Handoffs / follow-ups:",
		"      mu turn --session-kind operator --session-id <session-id> --body \"follow-up question\"",
		"      (without --session-kind, mu turn defaults to cp_operator sessions)",
		"",
		"    In-session /mu helpers:",
		"      /mu plan on|off|status|phase|root|check|uncheck|toggle-step|reset",
		"      /mu subagents on|off|status|refresh|prefix|root|role|spawn",
		"",
		"  Replay",
		"    mu replay <root-id>/<issue-id>",
		"    mu replay <store>/logs/<root-id>/<issue-id>.jsonl",
		"",
		"  Messaging integrations (identity & config)",
		"    mu control status                     Summary of identities, policy, adapters",
		"    mu control status --json --pretty      Structured output",
		"    mu control link --channel telegram --actor-id 123 --tenant-id telegram-bot",
		"    mu control link --channel slack --actor-id U01 --tenant-id T01 --role viewer",
		"    mu control identities --pretty         List active bindings",
		"    mu control identities --all --pretty   Include inactive bindings",
		"    mu control unlink <binding-id>          Self-unlink",
		"    mu control unlink <binding-id> --revoke Admin revocation",
		"    mu control diagnose-operator            Inspect operator turn parse/runtime health",
		"",
		"    Workflow: link → serve → use",
		"      1) mu control link --channel telegram --actor-id 99 --tenant-id telegram-bot",
		"      2) mu serve  (picks up linked identities automatically)",
		"      3) Send commands via the linked channel",
		"",
		"    Roles:",
		"      operator     Full access (read, write, execute, admin)",
		"      contributor   Read + write + execute (no admin)",
		"      viewer        Read-only",
		"",
		"  Serve (API + terminal operator session)",
		"    mu serve",
		"    mu serve --port 3000",
		"    (mu serve immediately attaches terminal operator session; /exit/Ctrl+D/Ctrl+C detaches, server stays running)",
		"",
		"  Login / Auth",
		"    mu login --list",
		"    mu login openai-codex",
		"",
		"    Environment variable auth (no login needed):",
		"      OPENAI_API_KEY, ANTHROPIC_API_KEY, GOOGLE_API_KEY, etc.",
		"",
		"    Telegram bot replies require control_plane.adapters.telegram.bot_token in <store>/config.json.",
		"",
		"Roles (High Level)",
		"  mu supports role-tagged issues to coordinate work:",
		"    orchestrator: breaks down goals, assigns work, integrates results",
		"    worker: executes a single atomic issue end-to-end",
		"",
		"  Tip: use `mu issues ready --root <root-id>` to find ready leaf work tagged for agents.",
		"",
		"Troubleshooting",
		"  Store missing / empty:",
		"    Run `mu run` or `mu serve` once to auto-create workspace store files.",
		"",
		"  Ambiguous id prefix:",
		"    Use a longer prefix or the full id. Try: `mu issues list --limit 20`.",
		"",
		"  A run failed or got interrupted:",
		"    Use the recovery hints printed by `mu run`/`mu resume`, or try:",
		"      mu replay <root-id>/<issue-id>",
		"      mu resume <root-id> --max-steps 20",
		"",
		"  Reconnect terminal operator after disconnect:",
		"    Use `mu session` (or `mu session <session-id>`). Interactive mode requires a TTY.",
		"",
		"  Headless/SSH serve:",
		"    Port-forward the serve port as needed.",
		"    The same terminal hosts the operator session.",
		"",
		"  Too much ANSI color:",
		"    Set `NO_COLOR=1` (or unset it to re-enable color).",
	].join("\n");
}
