export function guideText(): string {
	return [
		"mu guide - in-CLI documentation",
		"",
		"Goal: you should not have to leave the CLI to understand what mu supports.",
		"",
		"Quickstart",
		"  1) Initialize the store at your repo root:",
		"       mu init",
		"",
		"  2) See what exists / what is ready:",
		"       mu status",
		"       mu issues ready --root <root-id>",
		"",
		"  3) Start a run (creates a root issue + runs the DAG loop):",
		'       mu run "Break down this goal and execute it"',
		"",
		"  4) Resume an interrupted run:",
		"       mu resume <root-id>",
		"",
		"Command Overview",
		"  mu init                         Create .mu/ store files + logs/ directory",
		"  mu status                       Human summary (or JSON with --json)",
		"  mu issues <subcmd>              Issue DAG operations (JSON)",
		"  mu forum <subcmd>               Forum operations (JSON)",
		"  mu run <prompt...>              Start a new DAG run",
		"  mu resume <root-id>             Resume a DAG run",
		"  mu replay <id|path>             Print a logged run (pi-only JSONL)",
		"  mu serve                        Start API + web UI for browsing issues/runs",
		"  mu login                        Authenticate with an AI provider (or use env vars)",
		"",
		".mu Store Layout",
		"  mu stores all state at the git repo root in `.mu/`:",
		"    .mu/",
		"      issues.jsonl   Issue DAG nodes (one JSON object per line)",
		"      forum.jsonl    Forum messages (one JSON object per line)",
		"      events.jsonl   Append-only event log (auditing / derived views)",
		"      logs/          Run logs (grouped by root issue id)",
		"",
		"  Logs are written under:",
		"    .mu/logs/<root-id>/<issue-id>*.jsonl",
		"",
		"Common Workflows",
		"",
		"  Initialize / Status",
		"    mu init",
		"    mu status",
		"    mu status --json --pretty",
		"",
		"  Issues (DAG)",
		'    mu issues create "Title" --body "Details" --priority 2 --tag node:agent',
		"    mu issues list --status open --limit 20",
		"    mu issues ready --root <root-id>",
		"    mu issues get <id-or-prefix> --pretty",
		"    mu issues update <id> --status in_progress",
		"    mu issues close <id> --outcome success",
		"",
		"  Forum",
		"    mu forum post issue:<id> -m \"status update\" --author worker",
		"    mu forum read issue:<id> --limit 20",
		"    mu forum topics --prefix issue: --limit 20",
		"",
		"  Run / Resume",
		"    mu run <prompt...> --max-steps 20",
		"    mu resume <root-id> --max-steps 20",
		"",
		"    Model overrides:",
		"      mu run \"...\" --provider openai-codex --model gpt-5.3-codex --reasoning high",
		"",
		"    Non-interactive / machine-readable:",
		"      mu run \"...\" --json",
		"",
		"    Raw backend stream (pi JSONL):",
		"      mu run \"...\" --raw-stream",
		"",
		"  Replay",
		"    mu replay <root-id>/<issue-id>",
		"    mu replay .mu/logs/<root-id>/<issue-id>.jsonl",
		"",
		"  Serve (API + Web UI)",
		"    mu serve",
		"    mu serve --port 5173 --api-port 3000 --no-open",
		"",
		"  Login / Auth",
		"    mu login --list",
		"    mu login openai-codex",
		"",
		"    Environment variable auth (no login needed):",
		"      OPENAI_API_KEY, ANTHROPIC_API_KEY, GOOGLE_API_KEY, etc.",
		"",
		"Roles (High Level)",
		"  mu supports role-tagged issues to coordinate work:",
		"    orchestrator: breaks down goals, assigns work, integrates results",
		"    worker: executes a single atomic issue end-to-end",
		"",
		"  Tip: use `mu issues ready --root <root-id>` to find ready leaf work tagged for agents.",
		"",
		"Troubleshooting",
		"  Store missing / empty:",
		"    Run `mu init` once at the start of a repo to create `.mu/`.",
		"",
		"  Ambiguous id prefix:",
		"    Use a longer prefix or the full id. Try: `mu issues list --limit 20`.",
		"",
		"  A run failed or got interrupted:",
		"    Use the recovery hints printed by `mu run`/`mu resume`, or try:",
		"      mu replay <root-id>/<issue-id>",
		"      mu resume <root-id> --max-steps 20",
		"",
		"  Headless/SSH serve:",
		"    Use `mu serve --no-open` and port-forward the printed ports.",
		"",
		"  Too much ANSI color:",
		"    Set `NO_COLOR=1` (or unset it to re-enable color).",
	].join("\n");
}

